### ISSUE TITLE
Remove requirement for "@" in username when on self-hosted server

### ISSUE THREAD

**Issue by patcon** [WhisperSystems/Flock#80]
It's kinda minor, but curious: is this requirement strictly necessary?

**Comment by rhodey** [comment]
This is no doubt a silly requirement but unfortunately necessary due to oddities in the CalendarProvider built into Android :|

When creating a calendar on Android you must provide an "owner" property, it is required that this property be in the form of an email address though it doesn't actually have to be a valid email. The Events tables in the CalendarProvider have an "organizer" property which must also take the form of an email address, too.

I wish we could drop this requirement!
