### ISSUE TITLE
flock starts not after installing

### ISSUE THREAD

**Issue by wegawega** [WhisperSystems/Flock#90]
Hello,
I have installed flock and wanted it to start, but it starts not.
It crashed.
I have it deinstalled and once more installed, but it is the same reaction,  it crashed in the first second.
What can I do?
(My English is not so goot, please use simple english for me, thankyou.)

Best - wega

**Comment by wegawega** [comment]
P.S: I have it from the google-store.
I have android kitkat on sony tablet Z3.

**Comment by rhodey** [comment]
Thanks for opening this issue @wegawega, I was able to reproduce this issue on my Nexus 7.

The bug is that the XML layout design file for tablets is missing the `android:id="@+id/flock_description"` property, right now it is [this](https://github.com/WhisperSystems/Flock/blob/master/flock/src/main/res/layout-sw600dp/fragment_intro.xml#L41) but should be like [this](https://github.com/WhisperSystems/Flock/blob/master/flock/src/main/res/layout/fragment_intro.xml#L41)

This is an easy fix, I'll try to get an updated release on the Google Play Store as soon as possible. Thanks again!

**Comment by rhodey** [comment]
resolved by bbff2a5a344f8b828ea8cf65bf86bec94b52d833
